### ISSUE TITLE
crop_aligned_slice is set to False

### ISSUE THREAD

**Issue by latent-reason** [rg314/pytraction#53]
I just realized that I pushed with non default configs! 

Please make sure that `crop_aligned_slice` is set to `True`

```
settings:
  bead_channel: 0
  cell_channel: 1
  segment: False
  device: cpu
  crop_aligned_slice: True
```

_Originally posted by @rg314 in https://github.com/rg314/pytraction/issues/52#issuecomment-891669090_
